development:
  sessions:
    default:
      database: podcast_sync_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: podcast_sync_test
      hosts:
        - localhost:27017
